apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
  name: demo
spec:
  image: quay.io/app-sre/unleash-pko:latest
  config:
    unleash:
      host: test-unleash-goberlec.apps.appint-ex-01.e7t8.p1.openshiftapps.com
      common_secret: demo-config
      tenant_secret: tenent-secret
    db:
      admin_secret: creds
      ssl: true
