apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: unleash
spec:
  scopes:
  - Namespaced
  phases:
  - name: predeploy
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  - probes:
    - cel:
        message: Route has not been admitted
        rule: self.status.ingress.all(i, i.conditions.all(c, c.type == "Admitted" && c.status == "True"))
    - cel:
        message: TLS cert or key not present on the Route
        rule: "'certificate' in self.spec.tls && 'key' in self.spec.tls"
    selector:
      kind:
        group: route.openshift.io
        kind: Route
  config:
    openAPIV3Schema:
      properties:
        unleash:
          type: object
          properties:
            image:
              type: string
              description: reference to the image containing unleash
              default: quay.io/app-sre/unleash
            imageTag:
              type: string
              description: tag of the image containing unleash
              default: UNLEASH_IMAGE_TAG
            replicas:
              description: number of replicas for the unleash deployment
              type: integer
              default: 1
            resources:
              type: object
              default: {}
              properties:
                limits:
                  type: object
                  default: {}
                  properties:
                    cpu:
                      type: string
                      description: CPU limit for the unleash container
                      default: 100m
                    memory:
                      type: string
                      description: Memory limit for the unleash container
                      default: 200Mi
                requests:
                  type: object
                  default: {}
                  properties:
                    cpu:
                      type: string
                      description: CPU request for the unleash container
                      default: 50m
                    memory:
                      type: string
                      description: Memory request for the unleash container
                      default: 100Mi
            host:
              type: string
              description: Host for the route
            letsEncryptIssuer:
              type: string
              description: Name of the letscrypt ClusterIssuer to be used for the route
              default: letsencrypt-prod-http
            common_secret:
              type: string
              description: Reference to the secret containing the common config
            tenant_secret:
              type: string
              description: Reference to the secret containing the tenant config
            service_account_name:
              type: string
              description: Name of the service account to use
          required:
          - host
          - common_secret
          - tenant_secret
        db:
          type: object
          properties:
            admin_secret:
              type: string
              description: Reference to the Admin DB secret
            ssl:
              type: boolean
              default: true
              description: Whether to use SSL for the database connection
          required:
          - admin_secret
          - ssl
      required:
      - unleash
      - db
      type: object
